controller_list:
    - name: husky_left_ur5
      action_ns: follow_joint_trajectory
      default: true
      type: FollowJointTrajectory
      joints: [l_ur5_arm_shoulder_pan_joint, l_ur5_arm_shoulder_lift_joint, l_ur5_arm_elbow_joint, l_ur5_arm_wrist_1_joint, l_ur5_arm_wrist_2_joint, l_ur5_arm_wrist_3_joint]
    - name: husky_right_ur5
      action_ns: follow_joint_trajectory
      default: true
      type: FollowJointTrajectory
      joints: [r_ur5_arm_shoulder_pan_joint, r_ur5_arm_shoulder_lift_joint, r_ur5_arm_elbow_joint, r_ur5_arm_wrist_1_joint, r_ur5_arm_wrist_2_joint, r_ur5_arm_wrist_3_joint]
#    - name: husky_ptu
#      action_ns: husky_ptu
#      default: true
#      type: JointStateController
#      joints: [husky_ptu_pan, husky_ptu_tilt]
